package gojustext

var HaitianStoplist = map[string]bool {"nan": true,
"yon": true,
"se": true,
"ayisyen": true,
"vil": true,
"lang": true,
"ki": true,
"lane": true,
"Etazini.": true,
"Kiba": true,
"pou": true,
"ak": true,
"peyi": true,
"eta": true,
"moun": true,
"Li": true,
"gen": true,
"an": true,
"Popilasyon": true,
"pwovens": true,
"menm": true,
"kò": true,
"Ayiti.": true,
"rive": true,
"li": true,
"pale": true,
"Kiba.": true,
"l.": true,
"dezyèm": true,
"Kreyòl": true,
"radyo": true,
"Relasyon": true,
"Kiba,": true,
}